######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 23:22:08 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += style.h
SOURCES += main.cpp style.cpp
