######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 28 09:36:25 2013
######################################################################

TEMPLATE = app
TARGET = Screensavers
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
