######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 10 21:53:29 2008
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = notepad
TEMPLATE = app


SOURCES += main.cpp\
        mainwindow.cpp

HEADERS  += mainwindow.h
RESOURCES += notepad.qrc
