#ifndef _msenum_h_
#define _msenum_h_

namespace Office {
    enum MsoArrowheadStyle{
		msoArrowheadDiamond           =0x5,
		msoArrowheadNone              =0x1,
		msoArrowheadOpen              =0x3,
		msoArrowheadOval              =0x6,
		msoArrowheadStealth           =0x4,
		msoArrowheadStyleMixed        =-2 ,
		msoArrowheadTriangle          =0x2,
	};

	enum MsoArrowheadLength{
		msoArrowheadLengthMedium      =0x2,
		msoArrowheadLengthMixed       =-2 ,
		msoArrowheadLong              =0x3,
		msoArrowheadShort             =0x1,
	};

	enum MsoAlignCmd{
		msoAlignBottoms               =0x5,
		msoAlignCenters               =0x1,
		msoAlignLefts                 =0x0,
		msoAlignMiddles               =0x4,
		msoAlignRights                =0x2,
		msoAlignTops                  =0x3,
	};

    enum MsoAutoShapeType{
		msoShape16pointStar           =0x5e,
		msoShape24pointStar           =0x5f,
		msoShape32pointStar           =0x60,
		msoShape4pointStar            =0x5b,
		msoShape5pointStar            =0x5c,
		msoShape8pointStar            =0x5d,
		msoShapeActionButtonBackorPrevious=0x81,
		msoShapeActionButtonBeginning =0x83,
		msoShapeActionButtonCustom    =0x7d,
		msoShapeActionButtonDocument  =0x86,
		msoShapeActionButtonEnd       =0x84,
		msoShapeActionButtonForwardorNext=0x82,
		msoShapeActionButtonHelp      =0x7f,
		msoShapeActionButtonHome      =0x7e,
		msoShapeActionButtonInformation=0x80,
		msoShapeActionButtonMovie     =0x88,
		msoShapeActionButtonReturn    =0x85,
		msoShapeActionButtonSound     =0x87,
		msoShapeArc                   =0x19,
		msoShapeBalloon               =0x89,
		msoShapeBentArrow             =0x29,
		msoShapeBentUpArrow           =0x2c,
		msoShapeBevel                 =0xf ,
		msoShapeBlockArc              =0x14,
		msoShapeCan                   =0xd ,
		msoShapeChevron               =0x34,
		msoShapeCircularArrow         =0x3c,
		msoShapeCloudCallout          =0x6c,
		msoShapeCross                 =0xb ,
		msoShapeCube                  =0xe ,
		msoShapeCurvedDownArrow       =0x30,
		msoShapeCurvedDownRibbon      =0x64,
		msoShapeCurvedLeftArrow       =0x2e,
		msoShapeCurvedRightArrow      =0x2d,
		msoShapeCurvedUpArrow         =0x2f,
		msoShapeCurvedUpRibbon        =0x63,
		msoShapeDiamond               =0x4 ,
		msoShapeDonut                 =0x12,
		msoShapeDoubleBrace           =0x1b,
		msoShapeDoubleBracket         =0x1a,
		msoShapeDoubleWave            =0x68,
		msoShapeDownArrow             =0x24,
		msoShapeDownArrowCallout      =0x38,
		msoShapeDownRibbon            =0x62,
		msoShapeExplosion1            =0x59,
		msoShapeExplosion2            =0x5a,
		msoShapeFlowchartAlternateProcess=0x3e,
		msoShapeFlowchartCard         =0x4b,
		msoShapeFlowchartCollate      =0x4f,
		msoShapeFlowchartConnector    =0x49,
		msoShapeFlowchartData         =0x40,
		msoShapeFlowchartDecision     =0x3f,
		msoShapeFlowchartDelay        =0x54,
		msoShapeFlowchartDirectAccessStorage=0x57,
		msoShapeFlowchartDisplay      =0x58,
		msoShapeFlowchartDocument     =0x43,
		msoShapeFlowchartExtract      =0x51,
		msoShapeFlowchartInternalStorage=0x42,
		msoShapeFlowchartMagneticDisk =0x56,
		msoShapeFlowchartManualInput  =0x47,
		msoShapeFlowchartManualOperation=0x48,
		msoShapeFlowchartMerge        =0x52,
		msoShapeFlowchartMultidocument=0x44,
		msoShapeFlowchartOffpageConnector=0x4a,
		msoShapeFlowchartOr           =0x4e,
		msoShapeFlowchartPredefinedProcess=0x41,
		msoShapeFlowchartPreparation  =0x46,
		msoShapeFlowchartProcess      =0x3d,
		msoShapeFlowchartPunchedTape  =0x4c,
		msoShapeFlowchartSequentialAccessStorage=0x55,
		msoShapeFlowchartSort         =0x50,
		msoShapeFlowchartStoredData   =0x53,
		msoShapeFlowchartSummingJunction=0x4d,
		msoShapeFlowchartTerminator   =0x45,
		msoShapeFoldedCorner          =0x10,
		msoShapeHeart                 =0x15,
		msoShapeHexagon               =0xa ,
		msoShapeHorizontalScroll      =0x66,
		msoShapeIsoscelesTriangle     =0x7 ,
		msoShapeLeftArrow             =0x22,
		msoShapeLeftArrowCallout      =0x36,
		msoShapeLeftBrace             =0x1f,
		msoShapeLeftBracket           =0x1d,
		msoShapeLeftRightArrow        =0x25,
		msoShapeLeftRightArrowCallout =0x39,
		msoShapeLeftRightUpArrow      =0x28,
		msoShapeLeftUpArrow           =0x2b,
		msoShapeLightningBolt         =0x16,
		msoShapeLineCallout1          =0x6d,
		msoShapeLineCallout1AccentBar =0x71,
		msoShapeLineCallout1BorderandAccentBar=0x79,
		msoShapeLineCallout1NoBorder  =0x75,
		msoShapeLineCallout2          =0x6e,
		msoShapeLineCallout2AccentBar =0x72,
		msoShapeLineCallout2BorderandAccentBar=0x7a,
		msoShapeLineCallout2NoBorder  =0x76,
		msoShapeLineCallout3          =0x6f,
		msoShapeLineCallout3AccentBar =0x73,
		msoShapeLineCallout3BorderandAccentBar=0x7b,
		msoShapeLineCallout3NoBorder  =0x77,
		msoShapeLineCallout4          =0x70,
		msoShapeLineCallout4AccentBar =0x74,
		msoShapeLineCallout4BorderandAccentBar=0x7c,
		msoShapeLineCallout4NoBorder  =0x78,
		msoShapeMixed                 =-2  ,
		msoShapeMoon                  =0x18,
		msoShapeNoSymbol              =0x13,
		msoShapeNotPrimitive          =0x8a,
		msoShapeNotchedRightArrow     =0x32,
		msoShapeOctagon               =0x6 ,
		msoShapeOval                  =0x9 ,
		msoShapeOvalCallout           =0x6b,
		msoShapeParallelogram         =0x2 ,
		msoShapePentagon              =0x33,
		msoShapePlaque                =0x1c,
		msoShapeQuadArrow             =0x27,
		msoShapeQuadArrowCallout      =0x3b,
		msoShapeRectangle             =0x1 ,
		msoShapeRectangularCallout    =0x69,
		msoShapeRegularPentagon       =0xc ,
		msoShapeRightArrow            =0x21,
		msoShapeRightArrowCallout     =0x35,
		msoShapeRightBrace            =0x20,
		msoShapeRightBracket          =0x1e,
		msoShapeRightTriangle         =0x8 ,
		msoShapeRoundedRectangle      =0x5 ,
		msoShapeRoundedRectangularCallout=0x6a,
		msoShapeSmileyFace            =0x11,
		msoShapeStripedRightArrow     =0x31,
		msoShapeSun                   =0x17,
		msoShapeTrapezoid             =0x3 ,
		msoShapeUTurnArrow            =0x2a,
		msoShapeUpArrow               =0x23,
		msoShapeUpArrowCallout        =0x37,
		msoShapeUpDownArrow           =0x26,
		msoShapeUpDownArrowCallout    =0x3a,
		msoShapeUpRibbon              =0x61,
		msoShapeVerticalScroll        =0x65,
		msoShapeWave                  =0x67,
	};
    enum MsoAutomationSecurity{
		msoAutomationSecurityByUI     =0x2 ,
		msoAutomationSecurityForceDisable=0x3 ,
		msoAutomationSecurityLow      =0x1 ,
	};

	enum MsoCalloutDropType{
		msoCalloutDropBottom          =0x4,
		msoCalloutDropCenter          =0x3,
		msoCalloutDropCustom          =0x1,
		msoCalloutDropMixed           =-2 ,
		msoCalloutDropTop             =0x2,
	};

    enum MsoCalloutAngleType{
		msoCalloutAngle30             =0x2 ,
		msoCalloutAngle45             =0x3 ,
		msoCalloutAngle60             =0x4 ,
		msoCalloutAngle90             =0x5 ,
		msoCalloutAngleAutomatic      =0x1 ,
		msoCalloutAngleMixed          =-2  ,
	};

	enum MsoCalloutType{
		msoCalloutFour                =0x4,
		msoCalloutMixed               =-2 ,
		msoCalloutOne                 =0x1,
		msoCalloutThree               =0x3,
		msoCalloutTwo                 =0x2,
	};

	enum MsoColorType{
		msoColorTypeCMS               =0x4,
		msoColorTypeCMYK              =0x3,
		msoColorTypeInk               =0x5,
		msoColorTypeMixed             =-2 ,
		msoColorTypeRGB               =0x1,
		msoColorTypeScheme            =0x2,
	};

	enum MsoConnectorType{
		msoConnectorCurve             =0x3,
		msoConnectorElbow             =0x2,
		msoConnectorStraight          =0x1,
		msoConnectorTypeMixed         =-2 ,
	};

    enum MsoDiagramNodeType{
		msoDiagramAssistant           =0x2,
		msoDiagramNode                =0x1,
	};

    enum MsoDistributeCmd{
		msoDistributeHorizontally     =0x0 ,
		msoDistributeVertically       =0x1 ,
	};

    enum MsoDiagramType{
		msoDiagramCycle               =0x2 ,
		msoDiagramMixed               =-2  ,
		msoDiagramOrgChart            =0x1 ,
		msoDiagramPyramid             =0x4 ,
		msoDiagramRadial              =0x3 ,
		msoDiagramTarget              =0x6 ,
		msoDiagramVenn                =0x5 ,
	};

	enum MsoEditingType{
		msoEditingAuto                =0x0 ,
		msoEditingCorner              =0x1 ,
		msoEditingSmooth              =0x2 ,
		msoEditingSymmetric           =0x3 ,
	};
    
	enum MsoEncoding{
		msoEncodingArabic             =0x4e8  ,
		msoEncodingArabicASMO         =0x2c4  ,
		msoEncodingArabicAutoDetect   =0xc838 ,
		msoEncodingArabicTransparentASMO=0x2d0  ,
		msoEncodingAutoDetect         =0xc351 ,
		msoEncodingBaltic             =0x4e9  ,
		msoEncodingCentralEuropean    =0x4e2  ,
		msoEncodingCyrillic           =0x4e3  ,
		msoEncodingCyrillicAutoDetect =0xc833 ,
		msoEncodingEBCDICArabic       =0x4fc4 ,
		msoEncodingEBCDICDenmarkNorway=0x4f35 ,
		msoEncodingEBCDICFinlandSweden=0x4f36 ,
		msoEncodingEBCDICFrance       =0x4f49 ,
		msoEncodingEBCDICGermany      =0x4f31 ,
		msoEncodingEBCDICGreek        =0x4fc7 ,
		msoEncodingEBCDICGreekModern  =0x36b  ,
		msoEncodingEBCDICHebrew       =0x4fc8 ,
		msoEncodingEBCDICIcelandic    =0x5187 ,
		msoEncodingEBCDICInternational=0x1f4  ,
		msoEncodingEBCDICItaly        =0x4f38 ,
		msoEncodingEBCDICJapaneseKatakanaExtended=0x4f42 ,
		msoEncodingEBCDICJapaneseKatakanaExtendedAndJapanese=0xc6f2 ,
		msoEncodingEBCDICJapaneseLatinExtendedAndJapanese=0xc6fb ,
		msoEncodingEBCDICKoreanExtended=0x5161 ,
		msoEncodingEBCDICKoreanExtendedAndKorean=0xc6f5 ,
		msoEncodingEBCDICLatinAmericaSpain=0x4f3c ,
		msoEncodingEBCDICMultilingualROECELatin2=0x366  ,
		msoEncodingEBCDICRussian      =0x5190 ,
		msoEncodingEBCDICSerbianBulgarian=0x5221 ,
		msoEncodingEBCDICSimplifiedChineseExtendedAndSimplifiedChinese=0xc6f7 ,
		msoEncodingEBCDICThai         =0x5166 ,
		msoEncodingEBCDICTurkish      =0x51a9 ,
		msoEncodingEBCDICTurkishLatin5=0x402  ,
		msoEncodingEBCDICUSCanada     =0x25   ,
		msoEncodingEBCDICUSCanadaAndJapanese=0xc6f3 ,
		msoEncodingEBCDICUSCanadaAndTraditionalChinese=0xc6f9 ,
		msoEncodingEBCDICUnitedKingdom=0x4f3d ,
		msoEncodingEUCChineseSimplifiedChinese=0xcae0 ,
		msoEncodingEUCJapanese        =0xcadc ,
		msoEncodingEUCKorean          =0xcaed ,
		msoEncodingEUCTaiwaneseTraditionalChinese=0xcaee ,
		msoEncodingEuropa3            =0x7149 ,
		msoEncodingExtAlphaLowercase  =0x5223 ,
		msoEncodingGreek              =0x4e5  ,
		msoEncodingGreekAutoDetect    =0xc835 ,
		msoEncodingHZGBSimplifiedChinese=0xcec8 ,
		msoEncodingHebrew             =0x4e7  ,
		msoEncodingIA5German          =0x4e8a ,
		msoEncodingIA5IRV             =0x4e89 ,
		msoEncodingIA5Norwegian       =0x4e8c ,
		msoEncodingIA5Swedish         =0x4e8b ,
		msoEncodingISCIIAssamese      =0xdeae ,
		msoEncodingISCIIBengali       =0xdeab ,
		msoEncodingISCIIDevanagari    =0xdeaa ,
		msoEncodingISCIIGujarati      =0xdeb2 ,
		msoEncodingISCIIKannada       =0xdeb0 ,
		msoEncodingISCIIMalayalam     =0xdeb1 ,
		msoEncodingISCIIOriya         =0xdeaf ,
		msoEncodingISCIIPunjabi       =0xdeb3 ,
		msoEncodingISCIITamil         =0xdeac ,
		msoEncodingISCIITelugu        =0xdead ,
		msoEncodingISO2022CNSimplifiedChinese=0xc435 ,
		msoEncodingISO2022CNTraditionalChinese=0xc433 ,
		msoEncodingISO2022JPJISX02011989=0xc42e ,
		msoEncodingISO2022JPJISX02021984=0xc42d ,
		msoEncodingISO2022JPNoHalfwidthKatakana=0xc42c ,
		msoEncodingISO2022KR          =0xc431 ,
		msoEncodingISO6937NonSpacingAccent=0x4f2d ,
		msoEncodingISO885915Latin9    =0x6fbd ,
		msoEncodingISO88591Latin1     =0x6faf ,
		msoEncodingISO88592CentralEurope=0x6fb0 ,
		msoEncodingISO88593Latin3     =0x6fb1 ,
		msoEncodingISO88594Baltic     =0x6fb2 ,
		msoEncodingISO88595Cyrillic   =0x6fb3 ,
		msoEncodingISO88596Arabic     =0x6fb4 ,
		msoEncodingISO88597Greek      =0x6fb5 ,
		msoEncodingISO88598Hebrew     =0x6fb6 ,
		msoEncodingISO88598HebrewLogical=0x96c6 ,
		msoEncodingISO88599Turkish    =0x6fb7 ,
		msoEncodingJapaneseAutoDetect =0xc6f4 ,
		msoEncodingJapaneseShiftJIS   =0x3a4  ,
		msoEncodingKOI8R              =0x5182 ,
		msoEncodingKOI8U              =0x556a ,
		msoEncodingKorean             =0x3b5  ,
		msoEncodingKoreanAutoDetect   =0xc705 ,
		msoEncodingKoreanJohab        =0x551  ,
		msoEncodingMacArabic          =0x2714 ,
		msoEncodingMacCroatia         =0x2762 ,
		msoEncodingMacCyrillic        =0x2717 ,
		msoEncodingMacGreek1          =0x2716 ,
		msoEncodingMacHebrew          =0x2715 ,
		msoEncodingMacIcelandic       =0x275f ,
		msoEncodingMacJapanese        =0x2711 ,
		msoEncodingMacKorean          =0x2713 ,
		msoEncodingMacLatin2          =0x272d ,
		msoEncodingMacRoman           =0x2710 ,
		msoEncodingMacRomania         =0x271a ,
		msoEncodingMacSimplifiedChineseGB2312=0x2718 ,
		msoEncodingMacTraditionalChineseBig5=0x2712 ,
		msoEncodingMacTurkish         =0x2761 ,
		msoEncodingMacUkraine         =0x2721 ,
		msoEncodingOEMArabic          =0x360  ,
		msoEncodingOEMBaltic          =0x307  ,
		msoEncodingOEMCanadianFrench  =0x35f  ,
		msoEncodingOEMCyrillic        =0x357  ,
		msoEncodingOEMCyrillicII      =0x362  ,
		msoEncodingOEMGreek437G       =0x2e1  ,
		msoEncodingOEMHebrew          =0x35e  ,
		msoEncodingOEMIcelandic       =0x35d  ,
		msoEncodingOEMModernGreek     =0x365  ,
		msoEncodingOEMMultilingualLatinI=0x352  ,
		msoEncodingOEMMultilingualLatinII=0x354  ,
		msoEncodingOEMNordic          =0x361  ,
		msoEncodingOEMPortuguese      =0x35c  ,
		msoEncodingOEMTurkish         =0x359  ,
		msoEncodingOEMUnitedStates    =0x1b5  ,
		msoEncodingSimplifiedChineseAutoDetect=0xc6f8 ,
		msoEncodingSimplifiedChineseGB18030=0xd698 ,
		msoEncodingSimplifiedChineseGBK=0x3a8  ,
		msoEncodingT61                =0x4f25 ,
		msoEncodingTaiwanCNS          =0x4e20 ,
		msoEncodingTaiwanEten         =0x4e22 ,
		msoEncodingTaiwanIBM5550      =0x4e23 ,
		msoEncodingTaiwanTCA          =0x4e21 ,
		msoEncodingTaiwanTeleText     =0x4e24 ,
		msoEncodingTaiwanWang         =0x4e25 ,
		msoEncodingThai               =0x36a  ,
		msoEncodingTraditionalChineseAutoDetect=0xc706 ,
		msoEncodingTraditionalChineseBig5=0x3b6  ,
		msoEncodingTurkish            =0x4e6  ,
		msoEncodingUSASCII            =0x4e9f ,
		msoEncodingUTF7               =0xfde8 ,
		msoEncodingUTF8               =0xfde9 ,
		msoEncodingUnicodeBigEndian   =0x4b1  ,
		msoEncodingUnicodeLittleEndian=0x4b0  ,
		msoEncodingVietnamese         =0x4ea  ,
		msoEncodingWestern            =0x4e4  ,
	};

	enum MsoExtrusionColorType{
		msoExtrusionColorAutomatic    =0x1 ,
		msoExtrusionColorCustom       =0x2 ,
		msoExtrusionColorTypeMixed    =-2  ,
	};

    enum MsoFeatureInstall{
		msoFeatureInstallNone         =0x0 ,
		msoFeatureInstallOnDemand     =0x1 ,
		msoFeatureInstallOnDemandWithUI=0x2 ,
	};

    enum MsoFileDialogType{
		msoFileDialogFilePicker       =0x3 ,
		msoFileDialogFolderPicker     =0x4 ,
		msoFileDialogOpen             =0x1 ,
		msoFileDialogSaveAs           =0x2 ,
	};

    enum MsoFlipCmd{
		msoFlipHorizontal             =0x0 ,
		msoFlipVertical               =0x1 ,
	};

    enum MsoFillType {
		msoFillBackground             =0x5 ,
		msoFillGradient               =0x3 ,
		msoFillMixed                  =-2  ,
		msoFillPatterned              =0x2 ,
		msoFillPicture                =0x6 ,
		msoFillSolid                  =0x1 ,
		msoFillTextured               =0x4 ,
	};

    enum MsoGradientStyle{
		msoGradientDiagonalDown       =0x4 ,
		msoGradientDiagonalUp         =0x3 ,
		msoGradientFromCenter         =0x7 ,
		msoGradientFromCorner         =0x5 ,
		msoGradientFromTitle          =0x6 ,
		msoGradientHorizontal         =0x1 ,
		msoGradientMixed              =-2  ,
		msoGradientVertical           =0x2 ,
	};

    enum MsoGradientColorType{
		msoGradientColorMixed         =-2 ,
		msoGradientOneColor           =0x1,
		msoGradientPresetColors       =0x3,
		msoGradientTwoColors          =0x2,
	};

	enum MsoHyperlinkType{
		msoHyperlinkInlineShape       =0x2 ,
		msoHyperlinkRange             =0x0 ,
		msoHyperlinkShape             =0x1 ,
	};

   enum MsoLanguageID{
		msoLanguageIDAfrikaans        =0x436 ,
		msoLanguageIDAlbanian         =0x41c ,
		msoLanguageIDAmharic          =0x45e ,
		msoLanguageIDArabic           =0x401 ,
		msoLanguageIDArabicAlgeria    =0x1401,
		msoLanguageIDArabicBahrain    =0x3c01,
		msoLanguageIDArabicEgypt      =0xc01 ,
		msoLanguageIDArabicIraq       =0x801 ,
		msoLanguageIDArabicJordan     =0x2c01,
		msoLanguageIDArabicKuwait     =0x3401,
		msoLanguageIDArabicLebanon    =0x3001,
		msoLanguageIDArabicLibya      =0x1001,
		msoLanguageIDArabicMorocco    =0x1801,
		msoLanguageIDArabicOman       =0x2001,
		msoLanguageIDArabicQatar      =0x4001,
		msoLanguageIDArabicSyria      =0x2801,
		msoLanguageIDArabicTunisia    =0x1c01,
		msoLanguageIDArabicUAE        =0x3801,
		msoLanguageIDArabicYemen      =0x2401,
		msoLanguageIDArmenian         =0x42b ,
		msoLanguageIDAssamese         =0x44d ,
		msoLanguageIDAzeriCyrillic    =0x82c ,
		msoLanguageIDAzeriLatin       =0x42c ,
		msoLanguageIDBasque           =0x42d ,
		msoLanguageIDBelgianDutch     =0x813 ,
		msoLanguageIDBelgianFrench    =0x80c ,
		msoLanguageIDBengali          =0x445 ,
		msoLanguageIDBosnian          =0x101a,
		msoLanguageIDBosnianBosniaHerzegovinaCyrillic=0x201a,
		msoLanguageIDBosnianBosniaHerzegovinaLatin=0x141a,
		msoLanguageIDBrazilianPortuguese=0x416 ,
		msoLanguageIDBulgarian        =0x402 ,
		msoLanguageIDBurmese          =0x455 ,
		msoLanguageIDByelorussian     =0x423 ,
		msoLanguageIDCatalan          =0x403 ,
		msoLanguageIDCherokee         =0x45c ,
		msoLanguageIDChineseHongKongSAR=0xc04 ,
		msoLanguageIDChineseMacaoSAR  =0x1404,
		msoLanguageIDChineseSingapore =0x1004,
		msoLanguageIDCroatian         =0x41a ,
		msoLanguageIDCzech            =0x405 ,
		msoLanguageIDDanish           =0x406 ,
		msoLanguageIDDivehi           =0x465 ,
		msoLanguageIDDutch            =0x413 ,
		msoLanguageIDDzongkhaBhutan   =0x851 ,
		msoLanguageIDEdo              =0x466 ,
		msoLanguageIDEnglishAUS       =0xc09 ,
		msoLanguageIDEnglishBelize    =0x2809,
		msoLanguageIDEnglishCanadian  =0x1009,
		msoLanguageIDEnglishCaribbean =0x2409,
		msoLanguageIDEnglishIndonesia =0x3809,
		msoLanguageIDEnglishIreland   =0x1809,
		msoLanguageIDEnglishJamaica   =0x2009,
		msoLanguageIDEnglishNewZealand=0x1409,
		msoLanguageIDEnglishPhilippines=0x3409,
		msoLanguageIDEnglishSouthAfrica=0x1c09,
		msoLanguageIDEnglishTrinidadTobago=0x2c09,
		msoLanguageIDEnglishUK        =0x809 ,
		msoLanguageIDEnglishUS        =0x409 ,
		msoLanguageIDEnglishZimbabwe  =0x3009,
		msoLanguageIDEstonian         =0x425 ,
		msoLanguageIDFaeroese         =0x438 ,
		msoLanguageIDFarsi            =0x429 ,
		msoLanguageIDFilipino         =0x464 ,
		msoLanguageIDFinnish          =0x40b ,
		msoLanguageIDFrench           =0x40c ,
		msoLanguageIDFrenchCameroon   =0x2c0c,
		msoLanguageIDFrenchCanadian   =0xc0c ,
		msoLanguageIDFrenchCotedIvoire=0x300c,
		msoLanguageIDFrenchHaiti      =0x3c0c,
		msoLanguageIDFrenchLuxembourg =0x140c,
		msoLanguageIDFrenchMali       =0x340c,
		msoLanguageIDFrenchMonaco     =0x180c,
		msoLanguageIDFrenchMorocco    =0x380c,
		msoLanguageIDFrenchReunion    =0x200c,
		msoLanguageIDFrenchSenegal    =0x280c,
		msoLanguageIDFrenchWestIndies =0x1c0c,
		msoLanguageIDFrenchZaire      =0x240c,
		msoLanguageIDFrisianNetherlands=0x462 ,
		msoLanguageIDFulfulde         =0x467 ,
		msoLanguageIDGaelicIreland    =0x83c ,
		msoLanguageIDGaelicScotland   =0x43c ,
		msoLanguageIDGalician         =0x456 ,
		msoLanguageIDGeorgian         =0x437 ,
		msoLanguageIDGerman           =0x407 ,
		msoLanguageIDGermanAustria    =0xc07 ,
		msoLanguageIDGermanLiechtenstein=0x1407,
		msoLanguageIDGermanLuxembourg =0x1007,
		msoLanguageIDGreek            =0x408 ,
		msoLanguageIDGuarani          =0x474 ,
		msoLanguageIDGujarati         =0x447 ,
		msoLanguageIDHausa            =0x468 ,
		msoLanguageIDHawaiian         =0x475 ,
		msoLanguageIDHebrew           =0x40d ,
		msoLanguageIDHindi            =0x439 ,
		msoLanguageIDHungarian        =0x40e ,
		msoLanguageIDIbibio           =0x469 ,
		msoLanguageIDIcelandic        =0x40f ,
		msoLanguageIDIgbo             =0x470 ,
		msoLanguageIDIndonesian       =0x421 ,
		msoLanguageIDInuktitut        =0x45d ,
		msoLanguageIDItalian          =0x410 ,
		msoLanguageIDJapanese         =0x411 ,
		msoLanguageIDKannada          =0x44b ,
		msoLanguageIDKanuri           =0x471 ,
		msoLanguageIDKashmiri         =0x460 ,
		msoLanguageIDKashmiriDevanagari=0x860 ,
		msoLanguageIDKazakh           =0x43f ,
		msoLanguageIDKhmer            =0x453 ,
		msoLanguageIDKirghiz          =0x440 ,
		msoLanguageIDKonkani          =0x457 ,
		msoLanguageIDKorean           =0x412 ,
		msoLanguageIDKyrgyz           =0x440 ,
		msoLanguageIDLao              =0x454 ,
		msoLanguageIDLatin            =0x476 ,
		msoLanguageIDLatvian          =0x426 ,
		msoLanguageIDLithuanian       =0x427 ,
		msoLanguageIDMacedonian       =0x42f ,
		msoLanguageIDMalayBruneiDarussalam=0x83e ,
		msoLanguageIDMalayalam        =0x44c ,
		msoLanguageIDMalaysian        =0x43e ,
		msoLanguageIDMaltese          =0x43a ,
		msoLanguageIDManipuri         =0x458 ,
		msoLanguageIDMaori            =0x481 ,
		msoLanguageIDMarathi          =0x44e ,
		msoLanguageIDMexicanSpanish   =0x80a ,
		msoLanguageIDMixed            =-2    ,
		msoLanguageIDMongolian        =0x450 ,
		msoLanguageIDNepali           =0x461 ,
		msoLanguageIDNoProofing       =0x400 ,
		msoLanguageIDNone             =0x0   ,
		msoLanguageIDNorwegianBokmol  =0x414 ,
		msoLanguageIDNorwegianNynorsk =0x814 ,
		msoLanguageIDOriya            =0x448 ,
		msoLanguageIDOromo            =0x472 ,
		msoLanguageIDPashto           =0x463 ,
		msoLanguageIDPolish           =0x415 ,
		msoLanguageIDPortuguese       =0x816 ,
		msoLanguageIDPunjabi          =0x446 ,
		msoLanguageIDQuechuaBolivia   =0x46b ,
		msoLanguageIDQuechuaEcuador   =0x86b ,
		msoLanguageIDQuechuaPeru      =0xc6b ,
		msoLanguageIDRhaetoRomanic    =0x417 ,
		msoLanguageIDRomanian         =0x418 ,
		msoLanguageIDRomanianMoldova  =0x818 ,
		msoLanguageIDRussian          =0x419 ,
		msoLanguageIDRussianMoldova   =0x819 ,
		msoLanguageIDSamiLappish      =0x43b ,
		msoLanguageIDSanskrit         =0x44f ,
		msoLanguageIDSepedi           =0x46c ,
		msoLanguageIDSerbianBosniaHerzegovinaCyrillic=0x1c1a,
		msoLanguageIDSerbianBosniaHerzegovinaLatin=0x181a,
		msoLanguageIDSerbianCyrillic  =0xc1a ,
		msoLanguageIDSerbianLatin     =0x81a ,
		msoLanguageIDSesotho          =0x430 ,
		msoLanguageIDSimplifiedChinese=0x804 ,
		msoLanguageIDSindhi           =0x459 ,
		msoLanguageIDSindhiPakistan   =0x859 ,
		msoLanguageIDSinhalese        =0x45b ,
		msoLanguageIDSlovak           =0x41b ,
		msoLanguageIDSlovenian        =0x424 ,
		msoLanguageIDSomali           =0x477 ,
		msoLanguageIDSorbian          =0x42e ,
		msoLanguageIDSpanish          =0x40a ,
		msoLanguageIDSpanishArgentina =0x2c0a,
		msoLanguageIDSpanishBolivia   =0x400a,
		msoLanguageIDSpanishChile     =0x340a,
		msoLanguageIDSpanishColombia  =0x240a,
		msoLanguageIDSpanishCostaRica =0x140a,
		msoLanguageIDSpanishDominicanRepublic=0x1c0a,
		msoLanguageIDSpanishEcuador   =0x300a,
		msoLanguageIDSpanishElSalvador=0x440a,
		msoLanguageIDSpanishGuatemala =0x100a,
		msoLanguageIDSpanishHonduras  =0x480a,
		msoLanguageIDSpanishModernSort=0xc0a ,
		msoLanguageIDSpanishNicaragua =0x4c0a,
		msoLanguageIDSpanishPanama    =0x180a,
		msoLanguageIDSpanishParaguay  =0x3c0a,
		msoLanguageIDSpanishPeru      =0x280a,
		msoLanguageIDSpanishPuertoRico=0x500a,
		msoLanguageIDSpanishUruguay   =0x380a,
		msoLanguageIDSpanishVenezuela =0x200a,
		msoLanguageIDSutu             =0x430 ,
		msoLanguageIDSwahili          =0x441 ,
		msoLanguageIDSwedish          =0x41d ,
		msoLanguageIDSwedishFinland   =0x81d ,
		msoLanguageIDSwissFrench      =0x100c,
		msoLanguageIDSwissGerman      =0x807 ,
		msoLanguageIDSwissItalian     =0x810 ,
		msoLanguageIDSyriac           =0x45a ,
		msoLanguageIDTajik            =0x428 ,
		msoLanguageIDTamazight        =0x45f ,
		msoLanguageIDTamazightLatin   =0x85f ,
		msoLanguageIDTamil            =0x449 ,
		msoLanguageIDTatar            =0x444 ,
		msoLanguageIDTelugu           =0x44a ,
		msoLanguageIDThai             =0x41e ,
		msoLanguageIDTibetan          =0x451 ,
		msoLanguageIDTigrignaEritrea  =0x873 ,
		msoLanguageIDTigrignaEthiopic =0x473 ,
		msoLanguageIDTraditionalChinese=0x404 ,
		msoLanguageIDTsonga           =0x431 ,
		msoLanguageIDTswana           =0x432 ,
		msoLanguageIDTurkish          =0x41f ,
		msoLanguageIDTurkmen          =0x442 ,
		msoLanguageIDUkrainian        =0x422 ,
		msoLanguageIDUrdu             =0x420 ,
		msoLanguageIDUzbekCyrillic    =0x843 ,
		msoLanguageIDUzbekLatin       =0x443 ,
		msoLanguageIDVenda            =0x433 ,
		msoLanguageIDVietnamese       =0x42a ,
		msoLanguageIDWelsh            =0x452 ,
		msoLanguageIDXhosa            =0x434 ,
		msoLanguageIDYi               =0x478 ,
		msoLanguageIDYiddish          =0x43d ,
		msoLanguageIDYoruba           =0x46a ,
		msoLanguageIDZulu             =0x435 ,
	};
    enum MsoLineStyle{
		msoLineSingle                 =0x1 ,
		msoLineStyleMixed             =-2  ,
		msoLineThickBetweenThin       =0x5 ,
		msoLineThickThin              =0x4 ,
		msoLineThinThick              =0x3 ,
		msoLineThinThin               =0x2 ,
	};

    enum MsoOrgChartLayoutType{
		msoOrgChartLayoutBothHanging  =0x2 ,
		msoOrgChartLayoutLeftHanging  =0x3 ,
		msoOrgChartLayoutMixed        =-2  ,
		msoOrgChartLayoutRightHanging =0x4 ,
		msoOrgChartLayoutStandard     =0x1 ,
	};

    enum MsoPresetMaterial{
		msoMaterialMatte              =0x1 ,
		msoMaterialMetal              =0x3 ,
		msoMaterialPlastic            =0x2 ,
		msoMaterialWireFrame          =0x4 ,
		msoPresetMaterialMixed        =-2  ,
	};

    enum MsoPresetLightingSoftness{
		msoLightingBright             =0x3 ,
		msoLightingDim                =0x1 ,
		msoLightingNormal             =0x2 ,
		msoPresetLightingSoftnessMixed=-2  ,
	};

    enum MsoPresetLightingDirection{
		msoLightingBottom             =0x8 ,
		msoLightingBottomLeft         =0x7 ,
		msoLightingBottomRight        =0x9 ,
		msoLightingLeft               =0x4 ,
		msoLightingNone               =0x5 ,
		msoLightingRight              =0x6 ,
		msoLightingTop                =0x2 ,
		msoLightingTopLeft            =0x1 ,
		msoLightingTopRight           =0x3 ,
		msoPresetLightingDirectionMixed=-2  ,
	};

    enum MsoPresetExtrusionDirection{
		msoExtrusionBottom            =0x2 ,
		msoExtrusionBottomLeft        =0x3 ,
		msoExtrusionBottomRight       =0x1 ,
		msoExtrusionLeft              =0x6 ,
		msoExtrusionNone              =0x5 ,
		msoExtrusionRight             =0x4 ,
		msoExtrusionTop               =0x8 ,
		msoExtrusionTopLeft           =0x9 ,
		msoExtrusionTopRight          =0x7 ,
		msoPresetExtrusionDirectionMixed=-2  ,
	};

    enum MsoPictureColorType{
		msoPictureAutomatic           =0x1,
		msoPictureBlackAndWhite       =0x3,
		msoPictureGrayscale           =0x2,
		msoPictureMixed               =-2 ,
		msoPictureWatermark           =0x4,
	};
    enum MsoLineDashStyle{
		msoLineDash                   =0x4,
		msoLineDashDot                =0x5,
		msoLineDashDotDot             =0x6,
		msoLineDashStyleMixed         =-2 ,
		msoLineLongDash               =0x7,
		msoLineLongDashDot            =0x8,
		msoLineRoundDot               =0x3,
		msoLineSolid                  =0x1,
		msoLineSquareDot              =0x2,
	};
    enum MsoPresetGradientType{
		msoGradientBrass              =0x14,
		msoGradientCalmWater          =0x8 ,
		msoGradientChrome             =0x15,
		msoGradientChromeII           =0x16,
		msoGradientDaybreak           =0x4 ,
		msoGradientDesert             =0x6 ,
		msoGradientEarlySunset        =0x1 ,
		msoGradientFire               =0x9 ,
		msoGradientFog                =0xa ,
		msoGradientGold               =0x12,
		msoGradientGoldII             =0x13,
		msoGradientHorizon            =0x5 ,
		msoGradientLateSunset         =0x2 ,
		msoGradientMahogany           =0xf ,
		msoGradientMoss               =0xb ,
		msoGradientNightfall          =0x3 ,
		msoGradientOcean              =0x7 ,
		msoGradientParchment          =0xe ,
		msoGradientPeacock            =0xc ,
		msoGradientRainbow            =0x10,
		msoGradientRainbowII          =0x11,
		msoGradientSapphire           =0x18,
		msoGradientSilver             =0x17,
		msoGradientWheat              =0xd ,
		msoPresetGradientMixed        =-2  ,
	};

	enum MsoPatternType{
		msoPattern10Percent           =0x2,
		msoPattern20Percent           =0x3,
		msoPattern25Percent           =0x4,
		msoPattern30Percent           =0x5,
		msoPattern40Percent           =0x6,
		msoPattern50Percent           =0x7,
		msoPattern5Percent            =0x1,
		msoPattern60Percent           =0x8,
		msoPattern70Percent           =0x9,
		msoPattern75Percent           =0xa,
		msoPattern80Percent           =0xb,
		msoPattern90Percent           =0xc,
		msoPatternDarkDownwardDiagonal=0xf,
		msoPatternDarkHorizontal      =0xd,
		msoPatternDarkUpwardDiagonal  =0x10   ,
		msoPatternDarkVertical        =0xe,
		msoPatternDashedDownwardDiagonal=0x1c   ,
		msoPatternDashedHorizontal    =0x20   ,
		msoPatternDashedUpwardDiagonal=0x1b   ,
		msoPatternDashedVertical      =0x1f   ,
		msoPatternDiagonalBrick       =0x28   ,
		msoPatternDivot               =0x2e   ,
		msoPatternDottedDiamond       =0x18   ,
		msoPatternDottedGrid          =0x2d   ,
		msoPatternHorizontalBrick     =0x23   ,
		msoPatternLargeCheckerBoard   =0x24   ,
		msoPatternLargeConfetti       =0x21   ,
		msoPatternLargeGrid           =0x22   ,
		msoPatternLightDownwardDiagonal=0x15   ,
		msoPatternLightHorizontal     =0x13   ,
		msoPatternLightUpwardDiagonal =0x16   ,
		msoPatternLightVertical       =0x14   ,
		msoPatternMixed               =-2 ,
		msoPatternNarrowHorizontal    =0x1e   ,
		msoPatternNarrowVertical      =0x1d   ,
		msoPatternOutlinedDiamond     =0x29   ,
		msoPatternPlaid               =0x2a   ,
		msoPatternShingle             =0x2f   ,
		msoPatternSmallCheckerBoard   =0x11   ,
		msoPatternSmallConfetti       =0x25   ,
		msoPatternSmallGrid           =0x17   ,
		msoPatternSolidDiamond        =0x27   ,
		msoPatternSphere              =0x2b   ,
		msoPatternTrellis             =0x12   ,
		msoPatternWave                =0x30   ,
		msoPatternWeave               =0x2c   ,
		msoPatternWideDownwardDiagonal=0x19   ,
		msoPatternWideUpwardDiagonal  =0x1a   ,
		msoPatternZigZag              =0x26   ,
	};

	enum MsoPresetTextEffect{
		msoTextEffect1                =0x0  ,
		msoTextEffect10               =0x9  ,
		msoTextEffect11               =0xa  ,
		msoTextEffect12               =0xb  ,
		msoTextEffect13               =0xc  ,
		msoTextEffect14               =0xd  ,
		msoTextEffect15               =0xe  ,
		msoTextEffect16               =0xf  ,
		msoTextEffect17               =0x10 ,
		msoTextEffect18               =0x11 ,
		msoTextEffect19               =0x12 ,
		msoTextEffect2                =0x1  ,
		msoTextEffect20               =0x13 ,
		msoTextEffect21               =0x14 ,
		msoTextEffect22               =0x15 ,
		msoTextEffect23               =0x16 ,
		msoTextEffect24               =0x17 ,
		msoTextEffect25               =0x18 ,
		msoTextEffect26               =0x19 ,
		msoTextEffect27               =0x1a ,
		msoTextEffect28               =0x1b ,
		msoTextEffect29               =0x1c ,
		msoTextEffect3                =0x2  ,
		msoTextEffect30               =0x1d ,
		msoTextEffect4                =0x3  ,
		msoTextEffect5                =0x4  ,
		msoTextEffect6                =0x5  ,
		msoTextEffect7                =0x6  ,
		msoTextEffect8                =0x7  ,
		msoTextEffect9                =0x8  ,
		msoTextEffectMixed            =-2   ,
	};
    enum MsoShapeType{
		msoAutoShape                  =0x1 ,
		msoCallout                    =0x2 ,
		msoCanvas                     =0x14,
		msoChart                      =0x3 ,
		msoComment                    =0x4 ,
		msoDiagram                    =0x15,
		msoEmbeddedOLEObject          =0x7 ,
		msoFormControl                =0x8 ,
		msoFreeform                   =0x5 ,
		msoGroup                      =0x6 ,
		msoInk                        =0x16,
		msoInkComment                 =0x17,
		msoLine                       =0x9 ,
		msoLinkedOLEObject            =0xa ,
		msoLinkedPicture              =0xb ,
		msoMedia                      =0x10,
		msoOLEControlObject           =0xc ,
		msoPicture                    =0xd ,
		msoPlaceholder                =0xe ,
		msoScriptAnchor               =0x12,
		msoShapeTypeMixed             =-2  ,
		msoTable                      =0x13,
		msoTextBox                    =0x11,
		msoTextEffect                 =0xf ,
	};
    enum MsoPresetTextEffectShape{
		msoTextEffectShapeArchDownCurve=0xa ,
		msoTextEffectShapeArchDownPour=0xe ,
		msoTextEffectShapeArchUpCurve =0x9 ,
		msoTextEffectShapeArchUpPour  =0xd ,
		msoTextEffectShapeButtonCurve =0xc ,
		msoTextEffectShapeButtonPour  =0x10,
		msoTextEffectShapeCanDown     =0x14,
		msoTextEffectShapeCanUp       =0x13,
		msoTextEffectShapeCascadeDown =0x28,
		msoTextEffectShapeCascadeUp   =0x27,
		msoTextEffectShapeChevronDown =0x6 ,
		msoTextEffectShapeChevronUp   =0x5 ,
		msoTextEffectShapeCircleCurve =0xb ,
		msoTextEffectShapeCirclePour  =0xf ,
		msoTextEffectShapeCurveDown   =0x12,
		msoTextEffectShapeCurveUp     =0x11,
		msoTextEffectShapeDeflate     =0x1a,
		msoTextEffectShapeDeflateBottom=0x1c,
		msoTextEffectShapeDeflateInflate=0x1f,
		msoTextEffectShapeDeflateInflateDeflate=0x20,
		msoTextEffectShapeDeflateTop  =0x1e,
		msoTextEffectShapeDoubleWave1 =0x17,
		msoTextEffectShapeDoubleWave2 =0x18,
		msoTextEffectShapeFadeDown    =0x24,
		msoTextEffectShapeFadeLeft    =0x22,
		msoTextEffectShapeFadeRight   =0x21,
		msoTextEffectShapeFadeUp      =0x23,
		msoTextEffectShapeInflate     =0x19,
		msoTextEffectShapeInflateBottom=0x1b,
		msoTextEffectShapeInflateTop  =0x1d,
		msoTextEffectShapeMixed       =-2  ,
		msoTextEffectShapePlainText   =0x1 ,
		msoTextEffectShapeRingInside  =0x7 ,
		msoTextEffectShapeRingOutside =0x8 ,
		msoTextEffectShapeSlantDown   =0x26,
		msoTextEffectShapeSlantUp     =0x25,
		msoTextEffectShapeStop        =0x2 ,
		msoTextEffectShapeTriangleDown=0x4 ,
		msoTextEffectShapeTriangleUp  =0x3 ,
		msoTextEffectShapeWave1       =0x15,
		msoTextEffectShapeWave2       =0x16,
	};

    enum MsoPresetThreeDFormat{
		msoPresetThreeDFormatMixed    =-2  ,
		msoThreeD1                    =0x1 ,
		msoThreeD10                   =0xa ,
		msoThreeD11                   =0xb ,
		msoThreeD12                   =0xc ,
		msoThreeD13                   =0xd ,
		msoThreeD14                   =0xe ,
		msoThreeD15                   =0xf ,
		msoThreeD16                   =0x10,
		msoThreeD17                   =0x11,
		msoThreeD18                   =0x12,
		msoThreeD19                   =0x13,
		msoThreeD2                    =0x2 ,
		msoThreeD20                   =0x14,
		msoThreeD3                    =0x3 ,
		msoThreeD4                    =0x4 ,
		msoThreeD5                    =0x5 ,
		msoThreeD6                    =0x6 ,
		msoThreeD7                    =0x7 ,
		msoThreeD8                    =0x8 ,
		msoThreeD9                    =0x9 ,
	};

    enum MsoRelativeNodePosition{
		msoAfterLastSibling           =0x4 ,
		msoAfterNode                  =0x2 ,
		msoBeforeFirstSibling         =0x3 ,
		msoBeforeNode                 =0x1 ,
	};

    enum MsoTargetBrowser{
		msoTargetBrowserIE4           =0x2,
		msoTargetBrowserIE5           =0x3,
		msoTargetBrowserIE6           =0x4,
		msoTargetBrowserV3            =0x0,
		msoTargetBrowserV4            =0x1,
	};

    enum MsoScreenSize{
		msoScreenSize1024x768         =0x4 ,
		msoScreenSize1152x882         =0x5 ,
		msoScreenSize1152x900         =0x6 ,
		msoScreenSize1280x1024        =0x7 ,
		msoScreenSize1600x1200        =0x8 ,
		msoScreenSize1800x1440        =0x9 ,
		msoScreenSize1920x1200        =0xa ,
		msoScreenSize544x376          =0x0 ,
		msoScreenSize640x480          =0x1 ,
		msoScreenSize720x512          =0x2 ,
		msoScreenSize800x600          =0x3 ,
	};

    enum MsoSyncEventType{
		msoSyncEventDownloadFailed    =0x2,
		msoSyncEventDownloadInitiated =0x0,
		msoSyncEventDownloadNoChange  =0x6,
		msoSyncEventDownloadSucceeded =0x1,
		msoSyncEventOffline           =0x7,
		msoSyncEventUploadFailed      =0x5,
		msoSyncEventUploadInitiated   =0x3,
		msoSyncEventUploadSucceeded   =0x4,
	};

    enum MsoTextEffectAlignment{
		msoTextEffectAlignmentCentered=0x2,
		msoTextEffectAlignmentLeft    =0x1,
		msoTextEffectAlignmentLetterJustify=0x4,
		msoTextEffectAlignmentMixed   =-2 ,
		msoTextEffectAlignmentRight   =0x3,
		msoTextEffectAlignmentStretchJustify=0x6,
		msoTextEffectAlignmentWordJustify=0x5,
	};

    enum MsoShadowType{
		msoShadow1                    =0x1 ,
		msoShadow10                   =0xa ,
		msoShadow11                   =0xb ,
		msoShadow12                   =0xc ,
		msoShadow13                   =0xd ,
		msoShadow14                   =0xe ,
		msoShadow15                   =0xf ,
		msoShadow16                   =0x10,
		msoShadow17                   =0x11,
		msoShadow18                   =0x12,
		msoShadow19                   =0x13,
		msoShadow2                    =0x2 ,
		msoShadow20                   =0x14,
		msoShadow3                    =0x3 ,
		msoShadow4                    =0x4 ,
		msoShadow5                    =0x5 ,
		msoShadow6                    =0x6 ,
		msoShadow7                    =0x7 ,
		msoShadow8                    =0x8 ,
		msoShadow9                    =0x9 ,
		msoShadowMixed                =-2  ,
	};

	enum MsoSegmentType{
		msoSegmentCurve               =0x1 ,
		msoSegmentLine                =0x0 ,
	};

    enum MsoPresetTexture{
		msoPresetTextureMixed         =-2  ,
		msoTextureBlueTissuePaper     =0x11,
		msoTextureBouquet             =0x14,
		msoTextureBrownMarble         =0xb ,
		msoTextureCanvas              =0x2 ,
		msoTextureCork                =0x15,
		msoTextureDenim               =0x3 ,
		msoTextureFishFossil          =0x7 ,
		msoTextureGranite             =0xc ,
		msoTextureGreenMarble         =0x9 ,
		msoTextureMediumWood          =0x18,
		msoTextureNewsprint           =0xd ,
		msoTextureOak                 =0x17,
		msoTexturePaperBag            =0x6 ,
		msoTexturePapyrus             =0x1 ,
		msoTextureParchment           =0xf ,
		msoTexturePinkTissuePaper     =0x12,
		msoTexturePurpleMesh          =0x13,
		msoTextureRecycledPaper       =0xe ,
		msoTextureSand                =0x8 ,
		msoTextureStationery          =0x10,
		msoTextureWalnut              =0x16,
		msoTextureWaterDroplets       =0x5 ,
		msoTextureWhiteMarble         =0xa ,
		msoTextureWovenMat            =0x4 ,
	};

    enum MsoScaleFrom{
		msoScaleFromBottomRight       =0x2 ,
		msoScaleFromMiddle            =0x1 ,
		msoScaleFromTopLeft           =0x0 ,
	};

    enum MsoTextOrientation{
		msoTextOrientationDownward    =0x3 ,
		msoTextOrientationHorizontal  =0x1 ,
		msoTextOrientationHorizontalRotatedFarEast=0x6 ,
		msoTextOrientationMixed       =-2  ,
		msoTextOrientationUpward      =0x2 ,
		msoTextOrientationVertical    =0x5 ,
		msoTextOrientationVerticalFarEast=0x4 ,
	};

    enum MsoTriState{
		msoCTrue                      =0x1,
		msoFalse                      =0x0,
		msoTriStateMixed              =-2 ,
		msoTriStateToggle             =-3 ,
		msoTrue                       =-1 ,
	};

    enum MsoZOrderCmd{
		msoBringForward               =0x2,
		msoBringInFrontOfText         =0x4,
		msoBringToFront               =0x0,
		msoSendBackward               =0x3,
		msoSendBehindText             =0x5,
		msoSendToBack                 =0x1,
	};

    enum MsoTextureType{
		msoTexturePreset              =0x1 ,
		msoTextureTypeMixed           =-2  ,
		msoTextureUserDefined         =0x2 ,
	};

	enum MsoArrowheadWidth{
		msoArrowheadNarrow            =0x1,
		msoArrowheadWide              =0x3,
		msoArrowheadWidthMedium       =0x2,
		msoArrowheadWidthMixed        =-2 ,
	};

}

#endif
